// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1982.Official2019.subsystems;


// import org.usfirst.frc1982.Official2019.commands.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.DoubleSolenoid;


public class Intake extends Subsystem {
    private final double intakeSpeed = 0.50;

    private WPI_TalonSRX wheelMotor;
    private DoubleSolenoid hatchGrabber;

    public Intake() {
        wheelMotor = new WPI_TalonSRX(8);
        wheelMotor.setInverted(true);
    
        hatchGrabber = new DoubleSolenoid(0, 3, 2);
        // addChild("hatchGrabber",hatchGrabber);
    }

    @Override
    public void initDefaultCommand() {
    }

    @Override
    public void periodic() {
    }

    public void extendHatchGrabber(){
        hatchGrabber.set(Value.kForward);
    }
    public void retractHatchGrabber(){
        hatchGrabber.set(Value.kReverse);
    }

    public void spinInward(){
        wheelMotor.set(intakeSpeed);
    }
    public void spinOutward(){
        wheelMotor.set(-1);
    }
    public void stopSpinning(){
        wheelMotor.set(0);
    }
    public void manualSpin(double speed){
        wheelMotor.set(speed);
    }
}